"""Change embedding vector type to VECTOR

Revision ID: a161b418900d
Revises: a992c17176a6
Create Date: 2025-08-03 16:40:54.937635

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a161b418900d"
down_revision: Union[str, Sequence[str], None] = "a992c17176a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        existing_nullable=False,
        postgresql_using="vector::vector",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
        existing_nullable=False,
        postgresql_using="vector::double precision[]",
    )
    # ### end Alembic commands ###
