name: Code Quality Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-format:
    name: Run Linter and Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run linter (Ruff)
        run: ruff check .

      - name: Check formatting (Black)
        run: black --check .
